# Generated by Django 4.1.7 on 2023-04-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_price_vacancy_salary_vacancy_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
