# Generated by Django 4.1.7 on 2023-04-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_company_address_company_city_company_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='price',
            new_name='salary',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default='Lolek description', max_length=255),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default='Lolek name', max_length=255),
        ),
    ]
